server:
  port: 8081

spring:
  application:
    name: config-server

logging:
  level:
    org.springframework.cloud.config: DEBUG


cloud:
  config:
    server:
      git:
        uri: https://github.com/AnibalGabrielAlmeida/ElectroStoreMicroservices.git
        searchPaths: config-data
        username: ${GIT_USER}
        password: ${GIT_PASSWORD}