server:
  port: 8081

spring:
  application:
    name: config-server

logging:
  level:
    root: DEBUG  # Establece el nivel de detalle general
    org.springframework.cloud.config: DEBUG  # Establece el nivel de detalle específico para el paquete relacionado con la configuración



cloud:
  config:
    server:
      git:
        uri: https://github.com/AnibalGabrielAlmeida/ElectroStoreMicroservices.git
        searchPaths: config-data
        username: ${GIT_USER}
        password: ${GIT_PASSWORD}